### ISSUE TITLE
Roadmap Planning

### ISSUE THREAD

**Issue by ironchain-dao** [ironchain-dao/DAO#1]
I listed some TODOs for us to start.

- [ ] What's our Mission?
- [ ] What's our org culture?
- [ ] The DAO structure
   - [ ] DAO Structure Proposal
   - [ ] Token Issuing and distribution policy
   - [ ] Channel setup(WeChat, Discord, Snapshot, Mirror)
- [ ] The very first program: NFT Auction
   - [ ] How to apply?
   - [ ] How to sell?
   - [ ] How to distribute?

**Comment by ironchain-dao** [comment]
Created two docs to collaborate:

DAO Structure and Token Plan:
https://docs.google.com/document/d/1PtgBQ9NRJpu7-YMzbZIEF9BfsOIXs2L-5ohxmaExUM0/edit

NFT Auction Workflow:
https://docs.google.com/document/d/1vWss0fXKQ1b6sQN-e-TBZ0v6t5GVKYYxhuxpZZDBGok/edit

**Comment by ironchain-dao** [comment]
抛砖引玉:

## Mission
关注女性权益，做到持续为女性发声，为需要的女性提供长效的法律和经济救助

## Culture
- 做对的事
- 追逐真相而非热点
